# Kinect (short-range mode) model taken from:
# Nguyen, C. V., Izadi, S., & Lovell, D. (2012).
# Modeling Kinect Sensor Noise for Improved 3D Reconstruction and Tracking.
sensor_processor/type: structured_light
sensor_processor/cutoff_min_depth: 0.35
sensor_processor/cutoff_max_depth: 3.0
sensor_processor/normal_factor_a: 0.0012
sensor_processor/normal_factor_b: 0.0019
sensor_processor/normal_factor_c: 0.4
sensor_processor/normal_factor_d: 0
sensor_processor/normal_factor_e: 1
sensor_processor/lateral_factor: 0.001376915 # for theta = 45Â°: 0.835 * 0.00780 [mm/px] / 4.73 [mm]
